#!/bin/sh

set -e

BUILD_DATE=`date`
BUILD_TIMESTAMP=`date +%Y%m%d%H%M`
BUILD_VERSION=$BUILD_TIMESTAMP
PROJECT_NAME="huayra-$ARCH"

if [ ! -z "$RELEASE_VERSION" ]; then
    BUILD_VERSION="$RELEASE_VERSION"
fi

# Archivo BUILD
echo "Versión: $BUILD_VERSION" > config/includes.binary/BUILD
echo $BUILD_DATE >> config/includes.binary/BUILD
cp -vf config/includes.binary/BUILD config/includes.chroot/BUILD

# Templates al binary
cat config/templates/isolinux/menu.cfg | sed -e "s/{{VERSION}}/$RELEASE_VERSION/" | sed -e "s/{{ARCH}}/$ARCH/"  > config/includes.binary/isolinux/menu.cfg
cat config/templates/isolinux/live-$ARCH.cfg | sed -e "s/{{VERSION}}/$RELEASE_VERSION/" | sed -e "s/{{ARCH}}/$ARCH/"  > config/includes.binary/isolinux/live.cfg
cat config/templates/isolinux/isolinux-$ARCH.cfg | sed -e "s/{{VERSION}}/$RELEASE_VERSION/" | sed -e "s/{{ARCH}}/$ARCH/"  > config/includes.binary/isolinux/isolinux.cfg
cat config/templates/README | sed -e "s/{{VERSION}}/$RELEASE_VERSION/" | sed -e "s/{{ARCH}}/$ARCH/"  > config/includes.binary/README


lb build noauto "${@}" 2>&1 | tee build.log
if [ -f live-image-$ARCH.hybrid.iso ]; then
  mv live-image-$ARCH.hybrid.iso $PROJECT_NAME-$BUILD_VERSION.iso
  mv live-image-$ARCH.contents $PROJECT_NAME-$BUILD_VERSION.contents
  mv live-image-$ARCH.packages $PROJECT_NAME-$BUILD_VERSION.packages
  mv live-image-$ARCH.files $PROJECT_NAME-$BUILD_VERSION.files
  mv chroot.files $PROJECT_NAME-$BUILD_VERSION.chroot.files
  mv chroot.packages.install $PROJECT_NAME-$BUILD_VERSION.chroot.packages.install
  mv chroot.packages.live $PROJECT_NAME-$BUILD_VERSION.chroot.packages.live
  mv build.log $PROJECT_NAME-$BUILD_VERSION.build.log
else
  test -f live-image-$ARCH.contents && mv live-image-$ARCH.contents $PROJECT_NAME-$BUILD_VERSION.contents.error
  test -f live-image-$ARCH.packages && mv live-image-$ARCH.packages $PROJECT_NAME-$BUILD_VERSION.packages.error
  test -f build.log && mv build.log $PROJECT_NAME-$BUILD_VERSION.build.log.error
  test -f live-image-$ARCH.files && mv live-image-$ARCH.files $PROJECT_NAME-$BUILD_VERSION.files.error
  test -f chroot.files && mv chroot.files $PROJECT_NAME-$BUILD_VERSION.chroot.files.error
  test -f chroot.packages.install && mv chroot.packages.install $PROJECT_NAME-$BUILD_VERSION.chroot.packages.install.error
  test -f chroot.packages.live && mv chroot.packages.live $PROJECT_NAME-$BUILD_VERSION.chroot.packages.live.error
fi

