#!/bin/bash
set -e

if [ -z "$CACHER" ]; then
  MIRROR="http://ftp.debian.org/debian/"
  MIRROR_SECURITY="http://security.debian.org/"
else
  MIRROR="http://$CACHER/ftp.debian.org/debian/"
  MIRROR_SECURITY="http://$CACHER/security.debian.org/"
fi

if [ -z "$ARCH" ]; then
    echo -e "ERROR: \n"
    echo -e "Se debe seleccionar la arquitectura usando la variable ARCH (i386|amd64)"
    echo -e "ejemplo: \n\tARCH=amd64 lb config\n"
    exit 1
fi

# Build segun arquitectura

if  [ "$ARCH" == "amd64" ]; then

    lb config noauto \
    --apt apt \
    --apt-options '--force-yes -y' \
    --apt-recommends false \
    --apt-source-archives true \
    --architectures amd64 \
    --archive-areas 'main contrib non-free' \
    --keyring-packages 'debian-archive-keyring huayra-archive-keyring' \
    --binary-images iso-hybrid \
    --debian-installer live \
    --debian-installer-gui true \
    --checksums md5 \
    --debug \
    --distribution jessie \
    --iso-application 'Huayra GNU/Linux' \
    --iso-publisher 'Conectar Igualdad; http://www.conectarigualdad.gob.ar/; info@conectarigualdad.gob.ar' \
    --iso-volume 'Huayra GNU/Linux' \
    --initsystem systemd \
    --linux-packages "linux-image linux-headers" \
    --zsync false \
    --loadlin false \
    --win32-loader false \
    --mirror-bootstrap $MIRROR \
    --parent-mirror-chroot $MIRROR \
    --parent-mirror-chroot-security $MIRROR_SECURITY \
    --mirror-debian-installer $MIRROR \
    --security true \
    --updates true \
    "${@}"

elif [ "$ARCH" == "i386" ]; then

    lb config noauto \
	--apt apt \
	--apt-options '--force-yes -y' \
	--apt-recommends false \
	--apt-source-archives true \
	--architectures i386 \
	--archive-areas 'main contrib non-free' \
	--keyring-packages 'debian-archive-keyring huayra-archive-keyring' \
	--bootappend-live 'hostname=huayra' \
	--binary-images iso-hybrid \
	--debian-installer live \
	--debian-installer-gui true \
	--checksums md5 \
	--debug \
	--distribution jessie \
	--iso-application 'Huayra GNU/Linux' \
	--iso-publisher 'Conectar Igualdad; http://www.conectarigualdad.gob.ar/; info@conectarigualdad.gob.ar' \
	--iso-volume 'Huayra GNU/Linux' \
	--initsystem systemd \
	--linux-packages "linux-image linux-headers" \
	--zsync false \
	--loadlin false \
	--win32-loader false \
	--mirror-bootstrap $MIRROR \
	--parent-mirror-chroot $MIRROR \
	--parent-mirror-chroot-security $MIRROR_SECURITY \
	--mirror-debian-installer $MIRROR \
	--security true \
	--updates true \
	"${@}"

fi
